# Generated by Django 4.1.2 on 2022-11-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(null=True, upload_to="profile_photos/"),
        ),
    ]
