# Generated by Django 4.1.2 on 2022-11-08 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0005_messagelikes"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MessageLikes",
            new_name="MessageLike",
        ),
    ]
