# Generated by Django 4.1.2 on 2022-11-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_message_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(default=False),
        ),
    ]
