# Generated by Django 4.1.2 on 2022-11-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_message_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="forvarded",
            field=models.BooleanField(default=False),
        ),
    ]
