# Generated by Django 4.1.2 on 2022-11-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_message_forvarded"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="forvarded",
            new_name="forwarded",
        ),
    ]
